WIP: Support forwarding of multi-package requests
openSUSE/open-build-service pull request #10026
Opened 2020-08-18 22:20 UTC by krauselukas

The PR is in state WIP, since a couple of code parts are not adapted yet, more refactoring is needed and adjustment of test are required.

Fixes #890

2020-08-19 11:18 UTC, Vogtinator commented
Can there be an option to forward it as individual srs? That would be very welcome for openSUSE:Factory.

2020-08-19 11:33 UTC, krauselukas commented
> Can there be an option to forward it as individual srs? That would be very welcome for openSUSE:Factory.

@Vogtinator I will check what I can do there, if it is hard to manage in the context of this PR, I might create a follow up :) this would be needed because of the factory-auto bot, right?

2020-08-19 11:36 UTC, Vogtinator commented
> > Can there be an option to forward it as individual srs? That would be very welcome for openSUSE:Factory.
> 
> @Vogtinator I will check what I can do there, if it is hard to manage in the context of this PR, I might create a follow up :) this would be needed because of the factory-auto bot, right?

Thanks! factory-auto declines those because the whole staging workflow does not support multi-action srs for multiple reasons. None of the bots can deal with them properly AFAIK.

2020-08-19 12:00 UTC, krauselukas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix and refactor BsRequest related views and functions](https://trello.com/c/s0sJvb0G/1524-fix-and-refactor-bsrequest-related-views-and-functions)

2020-08-31 10:44 UTC, vpereira requested changes

2020-08-31 10:44 UTC, vpereira commented on src/api/app/services/bs_request_service/action_forwarder.rb
> +        forwarding_options.append(Hash[action.id, BsRequestActionService::Forwardable.new(action).possible_targets])
instead of `each` and `append` you could call `collect` on `@bs_request_actions` and reduce this method to one line

2020-08-31 10:44 UTC, vpereira commented on src/api/app/services/bs_request_service/action_forwarder.rb
> +          bs_request_action = @bs_request_actions.where(id: target['req_action_id']).first
Instead of `where(...).first` use `find_by(...)`

2020-08-31 10:44 UTC, vpereira commented on src/api/app/controllers/webui/request_controller.rb
> +        handle_forwarding
as we are setting the flash message already, shouldn't `handle_forwarding` be a job to run on background?

2023-01-12 09:51 UTC, dmarcoux commented
I'm trying to rebase this PR due to the file conflicts emerging from the Bootstrap 5 update... but this PR was created before we started to work on the `request_show_redesign` feature toggle. I don't think it makes sense to keep this PR as it is now. We need to adapt the changes for that feature toggle.

2023-01-12 09:54 UTC, dmarcoux commented
We're tracking this in https://trello.com/c/3PrsTB41/79-support-forwarding-of-multi-package-requests

2023-01-12 09:54 UTC, closed without merging