Introduce measurements for user states and user roles
openSUSE/open-build-service pull request #10360
Opened 2020-10-29 17:17 UTC by eduardoj

Co-authored-by: Saray Cabrera Padrón <scabrerapadron@suse.de>

2020-10-29 20:10 UTC, hennevogel requested changes

2020-10-29 20:13 UTC, hennevogel commented
Also we're getting to a level of queries we shouldn't do if we don't have rabbit configured IMHO.

How about adding `return unless CONFIG['amqp_options']` to the job?

2020-10-30 11:18 UTC, eduardoj commented
> Also we're getting to a level of queries we shouldn't do if we don't have rabbit configured IMHO.
> 
> How about adding `return unless CONFIG['amqp_options']` to the job?

I agree. Added.

2020-10-30 11:18 UTC, eduardoj commented on src/api/app/jobs/measurements_job.rb
> +    Role.global.pluck(:title).map { |role_title| "role_#{role_title.downcase}=#{Role.find_by(title: role_title).users.count}" }.join(',')
True. Removed.

2020-10-30 11:45 UTC, hennevogel approved these changes

2020-10-30 11:45 UTC, merged