Move action 'Cloud upload configuration' to sidebar
openSUSE/open-build-service pull request #10489
Opened 2020-11-25 17:13 UTC by krauselukas

**Before (responsive_ux)**
![Screenshot_2020-11-25 Open Build Service(3)](https://user-images.githubusercontent.com/22001671/100260538-d35ae680-2f49-11eb-9dcf-fb506c8f2db8.png)

**After (responsive_ux)**
![Screenshot_2020-11-25 Open Build Service(2)](https://user-images.githubusercontent.com/22001671/100260564-da81f480-2f49-11eb-9b5c-86f7e7e2808b.png)

2020-11-25 17:16 UTC, krauselukas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Revisit and move pending actions (generic VS contextual)](https://trello.com/c/wtYKbgJm/1572-revisit-and-move-pending-actions-generic-vs-contextual)

2020-11-26 10:37 UTC, dmarcoux commented
I've setup the cloud upload to review [here](https://obs-reviewlab.opensuse.org/krauselukas-move_action_cloud_upload_config/cloud/upload)

2020-11-26 10:40 UTC, dmarcoux approved these changes

2020-11-26 11:44 UTC, danidoni commented
Looks like the label of that link is a bit long. What about changing to `Cloud Configuration`like we have [here](https://obs-reviewlab.opensuse.org/krauselukas-move_action_cloud_upload_config/cloud/configuration)?

2020-11-26 11:57 UTC, vpereira requested changes
![Screenshot_2020-11-26_12-56-00](https://user-images.githubusercontent.com/37418/100348159-d35cf400-2fe6-11eb-8954-add7b6641998.png)

It is just for me that the text takes now two lines?

2020-11-26 12:12 UTC, krauselukas commented
> Looks like the label of that link is a bit long. What about changing it to `Cloud Configuration`like we have [this](https://obs-reviewlab.opensuse.org/krauselukas-move_action_cloud_upload_config/cloud/configuration) breadcrumb?

Yes, lets go with it, we also use 'Cloud configuration' in the breadcrumbs

2020-11-26 13:31 UTC, vpereira approved these changes

2020-11-26 13:31 UTC, merged