[api] fix place sourcediff in request diffing
openSUSE/open-build-service pull request #10511
Opened 2020-12-01 10:56 UTC by adrianschroeter

The sourcediff need to be part of the action where they belong to.

Not only the very fist action item.

(jsc#OBS-71)

2020-12-01 14:38 UTC, danidoni requested changes

2020-12-01 14:38 UTC, danidoni commented on src/api/app/controllers/request_controller.rb
> +        xml_request.at_xpath("//request/action[last()]").add_child(action_diff)
```suggestion
        xml_request.at_xpath('//request/action[last()]').add_child(action_diff)
```

2020-12-15 08:24 UTC, danidoni commented
I think this change is already in master [here](https://github.com/adrianschroeter/open-build-service/blob/b83eef7075e69dfca7628ac317b24d11ef10a73d/src/api/app/controllers/request_controller.rb#L190), am I wrong?

Can you try to rebase this PR against master and see if this change is still relevant?

2021-01-04 21:33 UTC, hennevogel commented
It's already there...

2021-01-04 21:33 UTC, closed without merging