Adds a unique index on the name column on the status_checks table
openSUSE/open-build-service pull request #10549
Opened 2020-12-11 09:17 UTC by danidoni

This PR addresses the [cop regarding an unique index missing](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railsuniquevalidationwithoutindex) detected by [this depfu PR](https://github.com/openSUSE/open-build-service/pull/10545)

If this PR requires any particular action or consideration before deployment,
please check the reasons or add your own to the list:

* [ ] Requires a database migration that can cause downtime. Postpone deployment until maintenance window[1].
* [ ] Contains a data migration that can cause temporary inconsistency, so should be run at a specific point of time.

2020-12-11 12:34 UTC, krauselukas requested changes
@danidoni If I'm not mistaken the validation here  https://github.com/openSUSE/open-build-service/blob/a37e0015fc7df83c642c16593f40e4c20fdb140b/src/api/app/models/status/check.rb#L19 is scoped. The name of a status check itself is not uniq. I think you have to do whats described here https://github.com/openSUSE/open-build-service/blob/a37e0015fc7df83c642c16593f40e4c20fdb140b/src/api/app/models/status/check.rb#L19

2020-12-11 13:43 UTC, danidoni commented
> @danidoni If I'm not mistaken the validation here
> 
> https://github.com/openSUSE/open-build-service/blob/a37e0015fc7df83c642c16593f40e4c20fdb140b/src/api/app/models/status/check.rb#L19
> is scoped. The name of a status check itself is not uniq. I think you have to do whats described here https://guides.rubyonrails.org/active_record_validations.html#uniqueness so to create a unique index on both columns.

You are so right! I've added the index for both columns. Please, check it out again.

2020-12-11 15:49 UTC, krauselukas approved these changes
LGTM

2020-12-14 13:11 UTC, danidoni commented
We need to wait for the next maintenance window to deploy this: Thursday, December 17th, 2020

2021-01-04 11:28 UTC, dmarcoux commented
Adding an index is safe with MariaDB, we don't need to wait for a maintenance window.

2021-01-04 11:39 UTC, merged

2021-01-07 07:53 UTC, dmarcoux commented
Reverted in #10545