Use an up to date distribution name
openSUSE/open-build-service pull request #10622
Opened 2021-01-13 16:45 UTC by danidoni

OpenQA tests were failing because we no longer have openSUSE Leap 15.1 in the
Repositories to add from.

2021-01-13 16:52 UTC, hennevogel requested changes

2021-01-13 16:52 UTC, hennevogel commented on dist/t/spec/features/0030_project_spec.rb
>      expect(page).to have_content("Successfully added repository 'openSUSE_Leap_15.1'")
```suggestion
    expect(page).to have_content("Successfully added repository 'openSUSE_Leap_15.3'")
```

2021-01-13 16:52 UTC, hennevogel commented on dist/t/spec/features/0030_project_spec.rb
> +    check('repo_openSUSE_Leap_15_2')
```suggestion
    check('repo_openSUSE_Leap_15_3')
```

2021-01-13 19:41 UTC, eduardoj approved these changes

2021-01-14 10:06 UTC, hennevogel approved these changes

2021-01-14 10:06 UTC, merged