Remove not needed path parameter for creating an issue tracker from apidocs documentation
openSUSE/open-build-service pull request #10628
Opened 2021-01-14 11:33 UTC by eduardoj

The `POST` route for issue trackers doesn't require an issue tracker id in path parameters. And the `create` method in the controller doesn't make use of any path parameters.

This is how issue_trackers routes looks like now:

```
issue_tracker_issue GET    /issue_trackers/:issue_tracker_id/issues/:id(.:format) issues#show                                                            
     issue_trackers GET    /issue_trackers(.:format)                              issue_trackers#index                                                   
                    POST   /issue_trackers(.:format)                              issue_trackers#create                                                  
      issue_tracker GET    /issue_trackers/:id(.:format)                          issue_trackers#show                                                    
                    PATCH  /issue_trackers/:id(.:format)                          issue_trackers#update                                                  
                    PUT    /issue_trackers/:id(.:format)                          issue_trackers#update                                                  
                    DELETE /issue_trackers/:id(.:format)                          issue_trackers#destroy                                                 
```

Also replace `bnc` as an example of ids with `<id>`, in the comments, for the description of the route related to the controller method.

-----------------

If this PR requires any particular action or consideration before deployment,
please check the reasons or add your own to the list:

* [ ] Requires a database migration that can cause downtime. Postpone deployment until maintenance window[1].
* [ ] Contains a data migration that can cause temporary inconsistency, so should be run at a specific point of time.
* [ ] Changes some configuration files (e.g. options.yml), so the changes have to be applied manually in the reference server.
* [ ] A new Feature Toggle[2] should be enabled in the reference server.
* [ ] Proper documentation or announcement has to be published upfront since the introduced changes can confuse the users.

[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#when-there-are-migrations
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-your-feature

2021-01-14 16:56 UTC, dmarcoux requested changes
The routes are expecting an id because this is the default for resources in Rails. However, it is really a name. We are retrieving the issue trackers with _IssueTracker.**find_by_name**(params[:id])_, so it's clearly a name.

I suggest renaming the default param from `id` to `name` since this is what it really is. This involves changing the routes. We would need to add `param: :name` to the resources defined in https://github.com/openSUSE/open-build-service/blob/6bf4751cebcd518bbeaaafc98b5113c0ec230842/src/api/config/routes/api_routes.rb#L74

We can then clear out the inconsistencies in the code and only use `param[:name]`. In the end, I wonder if those changes are worth the time. I understand if you don't want to go this far.

2021-01-14 16:56 UTC, dmarcoux commented on docs/api/api/api.txt
> +  Create new issue tracker.
Creating something already implies that it's new. I suggest going with:

```suggestion
  Create an issue tracker.
```

2021-01-14 16:56 UTC, dmarcoux commented on src/api/app/controllers/issue_trackers_controller.rb
> +  # PUT /issue_trackers/<id>
This is a name, not an id. Same for the other change in this file.

```suggestion
  # PUT /issue_trackers/<name>
```

2021-01-14 16:56 UTC, dmarcoux commented
Instead of `not needed` in the commit message, I suggest using `unneeded`

2021-01-14 18:59 UTC, eduardoj commented
@dmarcoux, I applied some of your sugestions in the existing commit, and added a couple of commits more:
- also following your suggestion, to use only `param[:name]`
- the last commit, to remove a line that was not used.

> We can then clear out the inconsistencies in the code and only use `param[:name]`. In the end, I wonder if those changes are worth the time. I understand if you don't want to go this far.

Let's do it, and hope for the best! :facepalm:

Please have a look again.

2021-01-15 11:12 UTC, danidoni approved these changes

2021-01-18 11:26 UTC, dmarcoux approved these changes

2021-01-18 12:19 UTC, merged