Remove package id from event table
openSUSE/open-build-service pull request #11181
Opened 2021-05-25 15:58 UTC by krauselukas

After changing the from the attempt of building an association
between an event and a package, to fetching the package
using the passed payload in the `ReportToScmJob`
in #11124
the package_id is not longer needed.

2021-05-25 15:59 UTC, krauselukas commented
![](https://github.trello.services/images/mini-trello-icon.png) [Remove the package field from Event](https://trello.com/c/gwg8uF61/1665-remove-the-package-field-from-event)

2021-05-25 16:38 UTC, hennevogel approved these changes

2021-05-27 08:06 UTC, dmarcoux requested changes
Ignoring the column and dropping it in the same PR is going to cause downtime. This has to be done separately:

Steps:
1. Merge first PR to ignore the column
2. Deploy changes from first PR
3. Merge second PR to drop the column
4. Deploy changes from second PR
5. Merge third PR to remove "ignore code" from first PR
6. Deploy changes from third PR

2021-05-27 09:08 UTC, dmarcoux approved these changes
Forget my previous review. I was wrong since we deploy changes by installing an RPM package, we're good. This is done in two steps, installing the package, then running the migration.

2021-05-27 09:30 UTC, merged