Recover from Sphinx connection errors on search
openSUSE/open-build-service pull request #11251
Opened 2021-06-17 08:07 UTC by danidoni

When the connection to the search service drops, shows an error message instead of crashing and logs the exception as well.

2021-06-17 09:07 UTC, danidoni commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make Sphinx integration more robust](https://trello.com/c/eh2z79U3/1691-make-sphinx-integration-more-robust)

2021-06-17 09:30 UTC, hennevogel requested changes

2021-06-17 09:30 UTC, hennevogel commented on src/api/app/controllers/webui/search_controller.rb
> +    flash[:error] = 'Error connecting to the search service.'
Not very helpful for you customers. What can they do about it? :)

And what about all the other exceptions that could occur?

2021-06-17 15:04 UTC, hennevogel commented on src/api/app/controllers/webui/search_controller.rb
> +    flash[:error] = 'Error connecting to the search service.'
> I think our customers can do nothing except wait until we fix whatever is the reason for the connection error. It's on our side to detect sphinx downtimes via monitoring and bring it back.

That's what you should tell them then.

2021-06-18 09:51 UTC, hennevogel commented
@danidoni you should squash commits

2021-06-21 07:53 UTC, dmarcoux approved these changes

2021-06-21 09:07 UTC, hennevogel approved these changes

2021-06-21 09:07 UTC, merged