Sanitize simple_format
openSUSE/open-build-service pull request #11320
Opened 2021-07-01 13:28 UTC by hennevogel

simple_format marks output as html safe. All of this data includes user input.
Through XML parsing we even store HTML in the database.

```
Xmlhash.parse('<project name="hans"><description>&lt;h2&gt;Hello World&lt;/h2&gt;</description></project>')
=> {"name"=>"hans", "description"=>"<h2>Hello World</h2>"}
```

So better sanitize the simple_format output.

_Replace this line with a description of your changes. Please follow the suggestions in the comment below._

2021-07-01 13:35 UTC, danidoni approved these changes

2021-07-01 13:55 UTC, eduardoj approved these changes

2021-07-01 15:12 UTC, dmarcoux requested changes
Does it really change something? Because according to the documentation of [simple_format](https://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-simple_format), this helper is already sanitizing the input. You need to explicitly set the `sanitize` option to `false` to not sanitize the input.

2021-07-02 12:37 UTC, hennevogel commented
> Does it really change something?

ARGL I forgot to append the allowed tags. Sorry, doing too many things at once...

2021-07-03 06:54 UTC, coolo commented
Now that asks for a DRY approach

2021-07-05 08:13 UTC, dmarcoux commented
So this change is only to sanitize `br` and `p` HTML tags, why? Is this really a problem if those 2 tags are not sanitized?

2021-07-05 08:16 UTC, coolo commented
the tags are the _allowed_ tags - they are not stripped. Basically Henne is after `<h2>` and co. But why `<p>` not `<div>`?

2021-07-05 08:16 UTC, dmarcoux commented
> the tags are the _allowed_ tags - they are not stripped.

:facepalm: Yes, I was checking that right now... hehehe

2021-07-05 10:01 UTC, hennevogel commented
> But why <p> not <div>?

Because `<p>` is the tag for paragraphs in `simple_format`

2021-07-05 10:10 UTC, hennevogel commented
> Now that asks for a DRY approach

I would rather have this explicit so people think about the consequences of this.

2021-07-05 10:16 UTC, eduardoj commented
> Now that asks for a DRY approach

`haml_lint` is reporting four issues. All of them are this error:
```
[W] RuboCop: Style/PercentLiteralDelimiters: `%w`-literals should be delimited by `[` and `]`.
```

No DRY approach asked, yet, IMHO.

2021-07-05 11:50 UTC, dmarcoux commented
> > Now that asks for a DRY approach
> 
> I would rather have this explicit so people think about the consequences of this.

It's easy to forget to have a tag. I prefer having an helper for this.

2021-07-05 13:15 UTC, dmarcoux approved these changes
I prefer to have an helper for this, but I won't fight for it.

2021-07-05 14:36 UTC, eduardoj approved these changes

2021-07-05 14:37 UTC, vpereira commented on src/api/app/views/layouts/webui/_flash.html.haml
> +              = sanitize(simple_format(@more_info), tags: %w[br p])
now it makes sense :+1:

2021-07-05 14:38 UTC, merged