Add removal of statistics#{download_counter,newest_stats} to release notes
openSUSE/open-build-service pull request #11430
Opened 2021-07-27 15:07 UTC by dmarcoux

Following up on #11422 and #11423. Just in case someone wonders.

2021-07-27 15:24 UTC, vpereira commented
do you want to drop it as well from Release Notes?

2021-07-27 18:31 UTC, dmarcoux commented
What do you mean the drop? Is mentioning that both endpoints have been removed not enough?

2021-07-28 09:54 UTC, hennevogel requested changes

2021-07-28 09:54 UTC, hennevogel commented on ReleaseNotes-2.11
> +   have been removed.
```suggestion
 * The API endpoints '/statistics/download_counter' and '/statistics/newest_stats'
   have been removed. They have been non-functional and unused for a long time.
```

2021-07-28 09:57 UTC, hennevogel approved these changes

2021-07-28 09:59 UTC, dmarcoux commented
I won't wait for CI to pass since this PR is only changing release notes.

2021-07-28 09:59 UTC, merged