Embargo handler
openSUSE/open-build-service pull request #11486
Opened 2021-08-10 11:50 UTC by vpereira

Extract code to check if a maintenance release is embargoed from the BsRequest model and move it to a helper class named `Project::EmbargoHandler` 

-----------------

If this PR requires any particular action or consideration before deployment,
please check the reasons or add your own to the list:

* [ ] Requires a database migration that can cause downtime. Postpone deployment until maintenance window[1].
* [ ] Contains a data migration that can cause temporary inconsistency, so should be run at a specific point of time.
* [ ] Changes some configuration files (e.g. options.yml), so the changes have to be applied manually in the reference server.
* [ ] A new Feature Toggle[2] should be enabled in the reference server.
* [ ] Proper documentation or announcement has to be published upfront since the introduced changes can confuse the users.

[1] https://github.com/openSUSE/open-build-service/wiki/Deployment-of-build.opensuse.org#when-there-are-migrations
[2] https://github.com/openSUSE/open-build-service/wiki/Feature-Toggles-%28Flipper%29#you-want-real-people-to-test-your-feature

2021-08-11 11:17 UTC, hennevogel requested changes

2021-08-11 11:22 UTC, vpereira commented on src/api/app/models/bs_request.rb
> +        Project::EmbargoHandler.new(project.name).call if source_project.is_a?(Project)
> source_project

i was faster fixing it :)

> why pass in the name and not the object

I just moved the code around, good question.

2021-08-11 11:32 UTC, vpereira commented on src/api/app/models/bs_request.rb
> +        Project::EmbargoHandler.new(project.name).call if source_project.is_a?(Project)
@hennevogel fixed.

2021-08-13 09:18 UTC, danidoni approved these changes

2021-08-13 09:19 UTC, hennevogel commented on src/api/app/models/project/embargo_handler.rb
> +      @embargo_date_attrib_type ||= AttribType.find_by_namespace_and_name!('OBS', 'EmbargoDate')
You call this exactly once but okay..

2021-08-13 09:22 UTC, hennevogel approved these changes

2021-08-13 09:24 UTC, merged