Fix spelling in comments
openSUSE/open-build-service pull request #11816
Opened 2021-11-06 20:37 UTC by Olf0

mantainer -> maintainer

2021-11-08 08:33 UTC, dmarcoux commented on src/api/test/functional/search_controller_test.rb
> +    # search for not mai
This comment should be on 1 line.

2021-11-08 19:47 UTC, Olf0 commented on src/api/test/functional/search_controller_test.rb
> +    # search for not mai
Ooops, sure: Fixed the broken fix now.

2021-11-09 08:42 UTC, danidoni approved these changes

2021-11-09 08:56 UTC, danidoni requested changes
@Olf0, can you please squash all the commits into just one? Then it's good to go.

2021-11-09 13:46 UTC, Olf0 commented
> @Olf0, can you please squash all the commits into just one? Then it's good to go.

I cannot see how this can be achieved at Github's web-frontend.
As I do not have a local copy, I will leave it here.  Sorry.

Proceed with is as you like.

2021-11-09 16:51 UTC, krauselukas commented
@Olf0 @danidoni squashed the commit for you

2021-11-09 16:51 UTC, krauselukas approved these changes

2021-11-09 17:50 UTC, hennevogel requested changes

2021-11-09 17:50 UTC, hennevogel commented on src/api/test/functional/search_controller_test.rb
> +    # search for not maintainer packages
While fixing the typo let's also fix the meaning. 
```suggestion
    # search for un-maintained packages
```

2021-11-09 17:50 UTC, hennevogel commented on src/api/test/functional/search_controller_test.rb
> +    # search for not maintainer packages
```suggestion
    # search for un-maintained packages
```

2021-11-09 17:51 UTC, hennevogel approved these changes

2021-11-10 02:27 UTC, Olf0 reviewed
Looking good.

2021-11-10 09:44 UTC, merged