Drop response_url from workflow_runs
openSUSE/open-build-service pull request #11850
Opened 2021-11-12 13:59 UTC by rubhanazeem

Initially, we thought that we needed the field response_url to report
back to SCM.  We just realise we are not responding back to SCM.

Co-authored-by: Eduardo Navarro <enavarro@suse.com>

2021-11-15 07:55 UTC, danidoni submitted a review, later dismissed

2021-11-15 17:07 UTC, krauselukas requested changes
@rubhanazeem I would suggest to first ignore the column as suggested here https://github.com/ankane/strong_migrations#removing-a-column

2021-11-16 10:34 UTC, krauselukas approved these changes
@rubhanazeem as we talked, the column was never used in the code, so there shouldnt be anything cached by active record. So its fine to migrate this without ignoring the column upfront

2021-11-16 10:35 UTC, merged

2021-11-16 10:39 UTC, dmarcoux commented
This column is to track the URL which we use to report back to the SCM. This isn't about reporting back to the SCM, it's about letting users know where exactly we reported back to. This PR should be reverted.