Rename "Show all" in notifications API and web UI
openSUSE/open-build-service pull request #11960
Opened 2021-12-09 12:08 UTC by dmarcoux

2021-12-09 12:08 UTC, dmarcoux commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rename "Show all" to "Show/Display up to X/Show more"](https://trello.com/c/TMaQQMJW/1808-rename-show-all-to-show-display-up-to-x-show-more)

2021-12-13 14:18 UTC, dmarcoux commented on src/api/public/apidocs-new/paths/my_notifications.yaml
> -      required: false
By default, parameters aren't required, so it doesn't have to be documented.

2021-12-13 15:20 UTC, saraycp approved these changes

2021-12-13 15:25 UTC, eduardoj commented on src/api/public/apidocs-new/paths/my_notifications.yaml
> +        type: int
```suggestion
        type: string
    - in: path
      name: show_maximum
      schema:
        type: string
```
According to [the documentation](https://swagger.io/docs/specification/data-models/data-types/#numbers), OpenAPI has two numeric types, `number` and `integer`. I would suggest to use `string`, as the current code doesn't strictly require an integer.

2021-12-13 16:32 UTC, saraycp requested changes

2021-12-13 16:32 UTC, saraycp commented on src/api/public/apidocs-new/paths/my_notifications.yaml
> +    - in: path
```suggestion
    - in: query
```

I'm going to open another PR to change the other parameters too and add a few more that are missing...

2021-12-13 17:07 UTC, eduardoj approved these changes

2021-12-13 17:10 UTC, saraycp approved these changes

2021-12-13 18:25 UTC, merged