Allow users to manage their own home project and its packages
openSUSE/open-build-service pull request #12808
Opened 2022-07-14 13:04 UTC by dmarcoux

This is needed since users sometimes remove themselves from the maintainers of their own home project. It should have never been possible in the first place for users to do this, but here we are.

For now, we can help users by applying this fix. This code from the custom authorization system is called in Pundit, so both authorization systems (custom and Pundit) are covered.

Fixes #10067

2022-07-14 13:21 UTC, dmarcoux commented on src/api/app/models/user.rb
> +  # rubocop:disable Metrics/PerceivedComplexity
Refactoring this method is clearly out of scope for this fix.

2022-07-15 10:33 UTC, danidoni approved these changes

2022-07-15 10:46 UTC, eduardoj requested changes
Failing tests in `spec/controllers/webui/package_controller_spec.rb` should be modified.

2022-07-18 09:21 UTC, dmarcoux commented on src/api/spec/controllers/webui/package_controller_spec.rb
> -    let(:package) { create(:package_with_revisions, name: 'package_with_one_revision', revision_count: 1, project: source_project) }
The specs were previously relying on a package in `source_project`, which the home project of `user`. Preventing a user from accessing the source of their own home project isn't possible anymore.

2022-07-18 09:48 UTC, eduardoj approved these changes
> Failing tests in `spec/controllers/webui/package_controller_spec.rb` should be modified.

The tests have been adapted. Looks good to me.

2022-07-18 10:39 UTC, merged