Downgrade nokogiri from 1.13.7 back to 1.13.6
openSUSE/open-build-service pull request #12825
Opened 2022-07-18 14:25 UTC by danidoni

This PR removes the need to upgrade nokogiri in #12801. That nokogiri upgrade requires ruby version >= 2.6.0 on [the 2.10 build](https://build.opensuse.org/package/show/OBS:Server:2.10:Staging/obs-server) and we don't want to upgrade ruby right now.

2022-07-18 14:52 UTC, hennevogel requested changes
explain yourself stanger!

2022-07-18 15:03 UTC, danidoni commented
> explain yourself stanger!

Yeah, sorry.

2022-07-19 08:01 UTC, danidoni commented
> The version numbers are wrong. _17_ should be _7_ and _16_ should be _6_.
> 
> Nokogiri _1.13.6_ still requires Ruby >= 2.6 as we can see here: https://rubygems.org/gems/nokogiri/versions/1.13.6. You would have to downgrade to _1.12.5_ to support Ruby >= 2.5 (see https://rubygems.org/gems/nokogiri/versions/1.12.5). We cannot do this though as we would have security vulnerabilities.

Thanks, you are right about the numbering, my bad.

About the ruby version I don't understand what's happening here: before the change that pulled in nokogiri v1.13.7 (#12801) we had nokogiri v1.13.6, and it was working fine with ruby version 2.5.9p229 :thinking:

2022-07-19 08:15 UTC, dmarcoux commented
It's possible that nokogiri _1.13.6_ worked with Ruby _2.5_, but the nokogiri developers aren't supporting this Ruby version anymore since nokogiri _1.12.5_. We can also stick to _1.13.6_, but nokogiri is somewhat often hit with security vulnerabilities.... so I guess it's a short/mid-term solution.

2022-07-19 10:07 UTC, hennevogel approved these changes

2022-07-19 10:36 UTC, merged