Document package copy command with OpenAPI
openSUSE/open-build-service pull request #13154
Opened 2022-09-29 13:05 UTC by danidoni

2022-10-05 15:19 UTC, hennevogel requested changes

2022-10-05 15:19 UTC, hennevogel commented on src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_copy.yaml
> +      description: Set to '1' to defer the copy to a background job.
```suggestion
      description: Set to '1' to do the copying synchronously. By default the copying is done asynchronously.
```

background job is an implementation detail...

2022-10-05 15:19 UTC, hennevogel commented on src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_copy.yaml
> +      description: Set to '1' to copy the package history.
```suggestion
      description: Set to '1' to copy the package commit history.
```

2022-10-05 15:19 UTC, hennevogel commented on src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_copy.yaml
> +      description: Copy binaries also.
```suggestion
      description: Copy binaries that have been build by the origin package too.
```

2022-10-05 15:19 UTC, hennevogel commented on src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_copy.yaml
> +          - 0
1 disables running services after the copy.

2022-10-05 16:36 UTC, danidoni commented on src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_copy.yaml
> +      description: Setting both makeolder and makeoriginolder will return an error back.
I still don't know... :/

2022-10-06 10:52 UTC, danidoni commented on src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_copy.yaml
> +      description: Setting both makeolder and makeoriginolder will return an error back.
Found it

2022-10-10 12:56 UTC, hennevogel approved these changes

2022-10-10 12:56 UTC, merged