Generalize tab anchor links
openSUSE/open-build-service pull request #13212
Opened 2022-10-13 07:13 UTC by eduardoj

2022-10-13 08:58 UTC, danidoni commented on src/api/app/views/webui/request/_actions_details.html.haml
> +  :plain
Shouldn't we use `:javascript` here?

2022-10-13 08:59 UTC, danidoni commented on src/api/app/views/webui/request/_actions_details.html.haml
> +  :plain
Also, we could push this into a `.js` file and call it unobstrusively from our asset pipeline

2022-10-13 12:10 UTC, danidoni commented on src/api/app/views/webui/request/_actions_details.html.haml
> +  :plain
Talked offline about this and it's usage is too specific to benefit from extracting into a javascript file

2022-10-13 13:29 UTC, hennevogel requested changes

2022-10-13 13:52 UTC, eduardoj commented on src/api/app/views/webui/request/beta_show.html.haml
> +    var tab_pane_id = document.location.hash.replace('#' + hash_prefix, '#') || $('.nav-tabs .nav-item:first-child .nav-link').attr('href');
I removed the default in the HTML.

If we leave the default in HTML, when browsing links pointing to other tabs which aren't the default ( /request/show/9#tab-pane-changes for example ) it happens some unwanted load effect:

![Peek 2022-10-13 15-51_request_workflow_redesign_nav_tabs_default](https://user-images.githubusercontent.com/24919/195615725-67db3470-49dd-4ae5-a4b3-8e25ef7dafd3.gif)

2022-10-14 10:17 UTC, hennevogel commented on src/api/app/views/webui/request/beta_show.html.haml
> +    var tab_pane_id = document.location.hash.replace('#' + hash_prefix, '#') || $('.nav-tabs .nav-item:first-child .nav-link').attr('href');
I see 👍🏿

2022-10-14 10:28 UTC, hennevogel approved these changes

2022-10-14 10:29 UTC, hennevogel commented
codecov hangs. [coverage is fine](https://app.circleci.com/pipelines/github/eduardoj/open-build-service/2426/workflows/8c3ea590-6fcd-429f-b295-91e8925fc879/jobs/16258). merging!

2022-10-14 10:29 UTC, merged