Add a badge selector
openSUSE/open-build-service pull request #13238
Opened 2022-10-19 10:09 UTC by hellcp-work

This is a companion PR to #13169, it's based on it, but I want this PR to be just about the selector.
![Screenshot from 2022-10-19 10-49-10](https://user-images.githubusercontent.com/114928900/196662590-d6ac4070-23fa-40e6-8a3a-c76121d6a047.png)

2022-10-27 12:54 UTC, hennevogel requested changes

2022-10-27 12:54 UTC, hennevogel commented on src/api/app/assets/javascripts/webui/badge.js
> +}
I think this is too much. People that build packages are capable of formating their links. I would display mardown and be done with it.

2022-10-27 13:37 UTC, hennevogel commented on src/api/.jshintrc
> +    "URL" :      false,
You don't use this anymore

2022-10-27 13:39 UTC, hennevogel approved these changes

2022-10-27 13:39 UTC, hennevogel commented
I like it

[![build result](https://obs-reviewlab.opensuse.org/hellcp-work-badge-selector/projects/home:Admin:hans/packages/ctris/badge.svg?type=default)](https://obs-reviewlab.opensuse.org/hellcp-work-badge-selector/package/show/home:Admin:hans/ctris)

2022-10-28 09:41 UTC, danidoni commented
> > No idea why feature spec fails
> 
> Explore the [artifacts](https://app.circleci.com/pipelines/github/openSUSE/open-build-service/8616/workflows/6b14e3c0-5629-4a22-93bf-c3c212a8e1b2/jobs/100225/artifacts) to understand why.

My guess is that the ui takes longer than the timeout value to finish loading and replace the spinner with some content that the spec is waiting for...

2022-10-28 09:58 UTC, hennevogel commented
> My guess is

Don't guess. Look at the artifacts. They tell you what's going on.

2022-11-03 16:36 UTC, hennevogel commented
I guess we should fix #13320 first

2022-12-19 13:54 UTC, danidoni approved these changes

2022-12-20 09:48 UTC, merged