[dist] add release notes for 2.10.19
openSUSE/open-build-service pull request #13530
Opened 2022-12-14 13:48 UTC by danidoni

2022-12-14 14:20 UTC, hennevogel commented on ReleaseNotes-2.10.19
> + *  fixup! [backend] Add support for qemu system emulated builds via bs_worker
ReleaseNotes are for admins, not for developers. You will have to turn this into an admin understandable sentence.

2022-12-14 14:20 UTC, hennevogel requested changes

2022-12-14 15:26 UTC, danidoni commented on ReleaseNotes-2.10.19
> + *  fixup! [backend] Add support for qemu system emulated builds via bs_worker
Changed the release note. What do you think?

2022-12-15 10:18 UTC, hennevogel approved these changes

2022-12-15 10:19 UTC, hennevogel commented
coveralls hangs, codecov is fine. merging

2022-12-15 10:19 UTC, merged