Workflow runs show view displays incorrect SCM name in webhook tab
openSUSE/open-build-service pull request #13828
Opened 2023-02-10 15:45 UTC by rubhanazeem

Gitea headers also contain headers of GitHub. To identify GitHub it is important to check the absence of gitea headers.

2023-02-10 15:48 UTC, rubhanazeem commented
![](https://github.trello.services/images/mini-trello-icon.png) [Workflow runs show view displays incorrect SCM name in webhook tab (S)](https://trello.com/c/8WIRCQMd/2115-workflow-runs-show-view-displays-incorrect-scm-name-in-webhook-tab-s)

2023-02-13 09:08 UTC, saraycp approved these changes
[This part of the Gitea documentation](https://docs.gitea.io/en-us/webhooks/#event-information) confirms that.

2023-02-13 09:53 UTC, danidoni commented
I believe we should trigger this use case in the specs and then confirm the fix against those specs.

2023-02-13 13:57 UTC, rubhanazeem commented on src/api/app/models/workflow_run.rb
> +    if parsed_request_headers['HTTP_X_GITHUB_EVENT'] && !parsed_request_headers['HTTP_X_GITEA_EVENT']
Yeah, that will work. Having simpler conditions make it easy to understand. I've swapped the order

2023-02-13 14:03 UTC, danidoni requested changes

2023-02-13 14:03 UTC, danidoni commented on src/api/spec/models/workflow_run_spec.rb
> +        expect(workflow_run.scm_vendor).to be(:github)
```suggestion
      subject { workflow_run.scm_vendor }
      it 'identifies GitHub' do
        expect(subject).to be(:github)
```
Then you can reuse the subject on the other context too. Using the subject block helps identifying what do you want to test.

2023-02-13 14:57 UTC, danidoni approved these changes

2023-02-13 15:05 UTC, merged