Only fetch one commit for the latest revision
openSUSE/open-build-service pull request #13872
Opened 2023-02-21 18:41 UTC by hellcp-work

This is intended to fix #13871, by performing a caching operation of just the latest commit if it wasn't cached already, and returning it quickly

2023-02-21 19:02 UTC, eduardoj commented on src/api/app/models/package.rb
> +      cache_revision_commits(doc)
This call will store in cache only one element. Is that what we want?

2023-02-22 14:25 UTC, eduardoj commented on src/api/app/models/package.rb
> +      cache_revision_commits(doc)
I see.

I hoped we could paginate through the `_history` using this endpoint of the backend API : https://github.com/openSUSE/open-build-service/blob/b637d1118d0c9b3a6937959a281fb01cd13e19df/src/backend/bs_srcserver#L7610

But it looks like it is not supported.

2023-02-22 16:48 UTC, hennevogel requested changes

2023-02-22 16:48 UTC, hennevogel commented on src/api/app/models/package.rb
> +  def cache_single_commit(revision)
All 3 methods can now be `cache_revisions(rev: nil)`, the only difference is how you fetch the `_history`.

2023-02-23 11:38 UTC, hennevogel approved these changes

2023-02-23 11:39 UTC, merged