Complete the documentation of the `project` and `package` parameters
openSUSE/open-build-service pull request #13915
Opened 2023-02-28 13:32 UTC by eduardoj

...  for the `/request?view=collection` API endpoints.

Related to #13911.

2023-02-28 17:03 UTC, hennevogel requested changes

2023-02-28 17:03 UTC, hennevogel commented on src/api/public/apidocs-new/components/parameters/request.yaml
> +    or requests which were assigned to be reviewed by this project.
```suggestion
    Limit the results to requests with this project as source or target,
    or requests which were assigned to be reviewed by the maintainers of this project.
```

2023-02-28 17:48 UTC, eduardoj commented on src/api/public/apidocs-new/components/parameters/request.yaml
> +    or requests which were assigned to be reviewed by this project.
Applied. Thanks!

2023-03-01 16:20 UTC, hennevogel approved these changes

2023-03-01 16:20 UTC, merged