Simplify staged information
openSUSE/open-build-service pull request #13961
Opened 2023-03-07 14:55 UTC by ncounter

$subject

Do not differentiate too much `staged` information between `for_project` and `for_group` scenarios.

2023-03-07 16:07 UTC, hennevogel commented
I am afraid neither the old version nor this new version makes sense. We need to talk about the staging workflow.

2023-03-09 11:11 UTC, hennevogel commented on src/api/app/controllers/webui/request_controller.rb
> +        name: staging_review.project,
People refer to this as `Staging:Something`. 

Some recent example from the [opensuse-factory](https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/X44WML3GTW3S7ZTZDZMEU4EUPOQVWDJU/) mailing list:

>  Staging:O: preparation work to identify the minimal list of 'i586' builds to enable in openSUSE:Factory to allow wine/steam to build/install

That's the reason you had this abbreviation in the code you removed

```
irb(main):003:0> target_project_name = 'openSUSE:Factory'
=> "openSUSE:Factory"
irb(main):004:0> 'openSUSE:Factory:Staging:O'[target_project_name.length + 1..]
=> "Staging:O"
``

2023-03-10 08:35 UTC, danidoni approved these changes

2023-03-28 09:33 UTC, ncounter commented
@hennevogel would you mind to take another look to the screenshots? I dried off some verbosity

2023-03-28 10:56 UTC, hennevogel requested changes

2023-03-28 10:56 UTC, hennevogel commented on src/api/app/views/webui/request/beta_show.html.haml
> +                = link_to 'staging project', @staging_status[:target_project_staging_url]
```suggestion
              %strong Waiting
              the be
              %mark.text-light.bg-staging.text-nowrap.text-decoration-underline
                = link_to 'staged', @staging_status[:target_project_staging_url]
```

2023-03-28 10:56 UTC, hennevogel commented on src/api/app/views/webui/request/beta_show.html.haml
> +                = link_to 'staging project', @staging_status[:target_project_staging_url]
Would match how people talk about this...

2023-03-30 10:39 UTC, hennevogel approved these changes

2023-03-30 10:40 UTC, merged