Deprecate broken endpoints source rebuild and wipe
openSUSE/open-build-service pull request #13998
Opened 2023-03-14 10:46 UTC by hellcp-work

The following two endpoints are broken and have working alternatives on the build side of the api, so we are deprecating them.

2023-03-14 10:49 UTC, hennevogel requested changes

2023-03-14 10:49 UTC, hennevogel commented on src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_rebuild.yaml
> +    See [https://github.com/openSUSE/open-build-service/issues/13997](https://github.com/openSUSE/open-build-service/issues/13997).
I don't think we need to point to github issues here. Instead you should tell people what to use instead 😸

2023-03-15 11:19 UTC, hennevogel approved these changes

2023-03-15 14:22 UTC, eduardoj approved these changes

2023-03-15 14:23 UTC, merged