Document POST `/source/{project_name}/{package_name}?cmd={branch,linktobranch}` endpoints
openSUSE/open-build-service pull request #14018
Opened 2023-03-16 09:08 UTC by hellcp-work

Old api links:
https://build.opensuse.org/apidocs/index#60
https://build.opensuse.org/apidocs/index#71

Links for reviewers:
https://obs-reviewlab.opensuse.org/hellcp-work-apidocs-sources-package-branch/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_branch
https://obs-reviewlab.opensuse.org/hellcp-work-apidocs-sources-package-branch/apidocs-new/index#/Sources%20-%20Packages/post_source__project_name___package_name__cmd_linktobranch

2023-03-16 13:24 UTC, eduardoj commented on src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_branch.yaml
> +    The default target is home:<user>:branches:<project>/<package>
This line gets rendered in Swagger-UI as `The default target is home::branches:/`. Could we adjust it?

2023-03-16 13:25 UTC, eduardoj approved these changes

2023-03-16 15:37 UTC, saraycp requested changes

2023-03-16 15:37 UTC, saraycp commented on src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_branch.yaml
I've found a few misspellings in this file and the others. I think it's easier if I push a commit with corrections on top of yours (feel free to squash it later). Are you ok @hellcp-work ?

2023-03-16 16:27 UTC, saraycp commented on src/api/public/apidocs-new/paths/source_project_name_package_name_cmd_branch.yaml
Commit pushed

2023-03-17 11:57 UTC, saraycp approved these changes

2023-03-17 11:59 UTC, eduardoj approved these changes

2023-03-17 11:59 UTC, merged