add loongarch64 support for open-build-service
openSUSE/open-build-service pull request #14125
Opened 2023-04-10 12:52 UTC by zhangwenlong8911

2023-04-11 08:04 UTC, adrianschroeter commented
pushed minor fixes and a data migration to add the arch.

I am also loonking into the build script, which seems to have incomplete support for loongarch64 atm. Did you build anything successfully using it already?
Do you know, if kvm already supported on loonarch64?

2023-04-11 11:07 UTC, zhangwenlong8911 commented
> pushed minor fixes and a data migration to add the arch.
> 
> I am also loonking into the build script, which seems to have incomplete support for loongarch64 atm. Did you build anything successfully using it already? Do you know, if kvm already supported on loonarch64?

I can build with a low version and use it in some projects, such as http://117.78.1.88/project/show/openEuler:22.03:LTS:LoongArch

kvm does not fully support loongarch64, but support work is in progress in an orderly manner, see the mailing list: lkml.org/lkml/2023/4/6/1613

2023-04-11 15:19 UTC, hennevogel approved these changes
for the frontend changes...

2023-04-11 16:25 UTC, eduardoj requested changes

2023-04-11 16:25 UTC, eduardoj commented on src/api/db/data/20230411174510_add_loongarch64.rb
> +class AddLoongarch64 < ActiveRecord::Migration[5.1]
```suggestion
class AddLoongarch64 < ActiveRecord::Migration[7.0]
```
This seems copy-pasted from other data migrations. I tested the data migration generator (`bin/rails generate data_migration ...`). It returned `ActiveRecord::Migration[7.0]`.

Is there any reason to not using the now 7.0 version default?

2023-04-11 16:29 UTC, eduardoj commented on src/api/db/data/20230411174510_add_loongarch64.rb
> +  def self.up
```suggestion
  def up
```

2023-04-17 12:42 UTC, zhangwenlong8911 commented
@eduardoj Does this pr still need to be revised, please help review the pr if you have time, thank you

2023-08-11 10:14 UTC, hennevogel commented
@adrianschroeter is this good to go (after rebase)?

2024-04-07 01:21 UTC, zhangwenlong8911 commented
@eduardoj @adrianschroeter please help review the pr if you have time, thank you

2024-05-03 10:56 UTC, merged