Move bugzilla_args into its own function
openSUSE/open-build-service pull request #14158
Opened 2023-04-13 15:18 UTC by hellcp-work

We can't set args in the proxy because it's overriding the args we provide later, so instead we have a common set of args that gets set to the appropriate user and api_key values

2023-04-13 15:30 UTC, hennevogel requested changes

2023-04-14 10:35 UTC, bmwiedemann approved these changes

2023-04-14 11:43 UTC, hennevogel approved these changes

2023-04-14 11:44 UTC, hennevogel commented
Codecov hangs. Coverage is fine though. See the checks. Merging!

2023-04-14 11:44 UTC, merged