Document comment endpoints
openSUSE/open-build-service pull request #14202
Opened 2023-04-21 12:24 UTC by hellcp-work

This is split into 4 commits for clarity, the first one adds the base structure and delete endpoint, the rest of the commits are pretty much the same thing 3 times

2023-04-24 13:46 UTC, hennevogel commented on src/api/public/apidocs-new/paths/comments_request_id.yaml
> +                summary: Couldn't find BsRequest with [WHERE `bs_requests`.`number` = ?]
This sounds like a bug to me...

2023-04-24 13:46 UTC, hennevogel commented on src/api/public/apidocs-new/paths/comments_project_project_name.yaml
> +                summary: Couldn't find Project with [WHERE `project`.`name` = ?]
Isn't this a bug?

2023-04-24 13:50 UTC, hennevogel commented on src/api/public/apidocs-new/paths/comments_request_id.yaml
> +                summary: Couldn't find BsRequest with [WHERE `bs_requests`.`number` = ?]
Sounds like we should track those...

2023-04-25 14:06 UTC, saraycp requested changes

2023-04-25 14:06 UTC, saraycp commented on src/api/public/apidocs-new/paths/comments_package_project_name_package_name.yaml
> +    description: Contents of the comment
```suggestion
    description: Content of the comment
```

2023-04-25 14:06 UTC, saraycp commented on src/api/public/apidocs-new/paths/comments_project_project_name.yaml
> +    description: Contents of the comment
```suggestion
    description: Content of the comment
```

2023-04-25 14:06 UTC, saraycp commented on src/api/public/apidocs-new/paths/comments_request_id.yaml
> +    description: Contents of the comment
```suggestion
    description: Content of the comment
```

2023-04-25 14:06 UTC, saraycp commented on src/api/public/apidocs-new/paths/comments_project_project_name.yaml
> +  summary: List all project comments
```suggestion
  summary: List all the project's comments
```

2023-04-25 14:06 UTC, saraycp commented on src/api/public/apidocs-new/paths/comments_project_project_name.yaml
> +  description: List all comments for the project.
```suggestion
  description: List all the comments for the project.
```

2023-04-25 14:06 UTC, saraycp commented on src/api/public/apidocs-new/paths/comments_project_project_name.yaml
> +    Create a comment for the project.
This can be one line

2023-04-25 14:06 UTC, saraycp commented on src/api/public/apidocs-new/paths/comments_request_id.yaml
> +  summary: List all request comments
```suggestion
  summary: List all the request's comments
```

2023-04-25 14:06 UTC, saraycp commented on src/api/public/apidocs-new/paths/comments_request_id.yaml
> +  description: List all comments for the request.
```suggestion
  description: List all the comments for the request.
```

2023-04-27 11:36 UTC, saraycp requested changes

2023-04-27 11:36 UTC, saraycp commented on src/api/public/apidocs-new/paths/comments_package_project_name_package_name.yaml
> +                summary: Couldn't find Package with [WHERE `package`.`name` = ?]
With `GET 'http://localhost:3000/comments/package/home:Admin/FAKE'`
I get another 404 response:
```
<status code="unknown_package">
  <summary>Package not found: home:Admin/FAKE</summary>
</status>
```

:thinking:

2023-04-27 11:36 UTC, saraycp commented on src/api/public/apidocs-new/paths/comments_project_project_name.yaml
> +                summary: Couldn't find Project with [WHERE `project`.`name` = ?]
Same here. 
With `GET 'http://localhost:3000/comments/project/FAKE'`

I get:

```
<status code="unknown_project">
  <summary>Project not found: FAKE</summary>
</status>
```

2023-04-27 12:55 UTC, saraycp approved these changes

2023-04-27 12:55 UTC, merged