Document all the `/staging/{staging_workflow_project}/excluded_requests` endpoints
openSUSE/open-build-service pull request #14218
Opened 2023-04-24 14:23 UTC by saraycp

2023-04-24 14:30 UTC, hennevogel requested changes

2023-04-24 14:30 UTC, hennevogel commented on src/api/public/apidocs-new/paths/staging_staging_workflow_project_excluded_requests.yaml
> +  description: List the requests excluded from the staging project associated to the specified project
```suggestion
  description: List the requests excluded from the staging associated to the specified project
```

2023-04-24 14:30 UTC, hennevogel commented on src/api/public/apidocs-new/paths/staging_staging_workflow_project_excluded_requests.yaml
> +  summary: List the requests excluded from the current staging workflow
`:post` is not list but add right?

2023-04-24 14:30 UTC, hennevogel commented on src/api/public/apidocs-new/paths/staging_staging_workflow_project_excluded_requests.yaml
> +  description: Stop excluding the request from the staging workflow by deleting the specified request from the list of exluded requests
```suggestion
  description: Stop excluding the request from the staging workflow.
```

2023-04-24 14:30 UTC, hennevogel commented on src/api/public/apidocs-new/paths/staging_staging_workflow_project_excluded_requests.yaml
> +    description: List of requests to be excluded from the staging workflow
```suggestion
    description: List of requests to stop excluding from the staging workflow
```

2023-04-24 14:30 UTC, hennevogel commented on src/api/public/apidocs-new/components/schemas/staging/excluded_requests.yaml
> +          example: Lorem ipsum dolor sit amet
I guess a real world example would make things easier to understand here..

2023-04-24 15:36 UTC, saraycp commented on src/api/public/apidocs-new/paths/staging_staging_workflow_project_excluded_requests.yaml
> +  summary: List the requests excluded from the current staging workflow
copy + paste is evil. Fixed!

2023-04-24 16:11 UTC, saraycp commented on src/api/public/apidocs-new/paths/staging_staging_workflow_project_excluded_requests.yaml
> +                sumary: "Project project_name doesn't have an associated Staging Workflow"
This typo is fixed here (and all the endpoints in this PR), the text in the code will be fixed with https://github.com/openSUSE/open-build-service/pull/14221.

2023-04-25 08:48 UTC, saraycp commented
I should use `project_name` to define all the staging-related endpoints. The filenames are going to change as well. I move this PR to draft until I adapt everything.

2023-04-25 14:57 UTC, danidoni approved these changes

2023-04-25 15:08 UTC, merged