Add "Update of the Base Distributions" section to the release notes
openSUSE/open-build-service pull request #14780
Opened 2023-08-08 12:57 UTC by eduardoj

2023-08-08 13:01 UTC, hennevogel approved these changes

2023-08-09 15:45 UTC, hennevogel requested changes

2023-08-09 15:45 UTC, hennevogel commented on ReleaseNotes-2.10.21
> +We have updated the base distribution of the appliance to Leap 15.4. We also
```suggestion
We have updated the base distribution of the appliance to Leap 15.5. We also
```

2023-08-09 15:49 UTC, eduardoj commented on ReleaseNotes-2.10.21
> +We have updated the base distribution of the appliance to Leap 15.4. We also
Applied. Thanks!

2023-08-09 17:33 UTC, merged