Document `GET /build/.../_buildenv` and `_statistics` API endpoints
openSUSE/open-build-service pull request #14804
Opened 2023-08-14 12:52 UTC by eduardoj

2023-08-14 15:54 UTC, hennevogel requested changes

2023-08-14 16:03 UTC, eduardoj commented on src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_package_name_buildenv.yaml
> +        # application/xml; charset=utf-8:
Yes. Do you see this a valid case to not to say the truth?

2023-08-15 09:04 UTC, hennevogel commented on src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_package_name_buildenv.yaml
> +        # application/xml; charset=utf-8:
Yeah as none of the usual tools that use the API give much about content headers...

2023-08-21 09:56 UTC, hennevogel commented on src/api/public/apidocs/paths/build_project_name_repository_name_architecture_name_package_name_buildenv.yaml
> +        # application/xml; charset=utf-8:
pushed

2023-08-21 10:03 UTC, hennevogel approved these changes

2023-08-21 10:31 UTC, merged