Introduce notifications for decisions on moderated objects
openSUSE/open-build-service pull request #14967
Opened 2023-09-26 08:29 UTC by danidoni

2023-09-26 16:22 UTC, saraycp requested changes

2023-09-27 23:37 UTC, saraycp commented
I wonder if it's better to create one event per decision-report. My last commit is a WIP of the possible implementation.
We can discuss whether to continue or drop it.

2023-09-28 07:14 UTC, saraycp commented
> I wonder if it's better to create one event per decision-report. My last commit is a WIP of the possible implementation.
> We can discuss whether to continue or drop it.

We already discussed it and concluded this is not needed. We are not going to mention specific reports but the reportable, which is the same for all the reports related to the decision that generates the event.

2023-09-28 07:15 UTC, saraycp approved these changes

2023-09-28 12:20 UTC, ncounter approved these changes

2023-09-28 12:30 UTC, merged