Redirect to root if anonymous
openSUSE/open-build-service pull request #15318
Opened 2023-12-05 12:45 UTC by hennevogel

Everything but root_path requires auth with this setup. No need to send people to :back if it will not work.

Fixes #15315

2023-12-05 13:37 UTC, adrianschroeter commented
The request is to return to the page. Going back to main page is the same as closing and reopening the tab.

2023-12-05 14:34 UTC, hennevogel commented
> Going back to main page is the same as closing and reopening the tab.

Which is exactly what you have to do now manually....

2023-12-05 15:41 UTC, bmwiedemann commented
The whole UX is still improvable, because currently, 
* I follow a link to https://build.suse.de/request/show/314640
* get redirected to /
* log in
* get sent to / again and
* now need to find the original link again, because it is not in the browser history.

One idea of improvement would be to allow a `osc login` to re-use the ssh-key auth for the browser.
Another idea would be to keep the original requested URL and send the user there after login.

2023-12-05 16:55 UTC, hennevogel commented
Depends on #15321

2023-12-07 17:09 UTC, eliroca commented
> @bmwiedemann:  Another idea would be to keep the original requested URL and send the user there after login.

I've been testing, and found a working patch for this, as mentioned in #15315 :
```
CONFIG['proxy_auth_login_page'] + "?ReturnTo=" + URI.encode_www_form_component(request.fullpath)
```
Then we can work with that `ReturnTo` to redirect the user there.

2023-12-12 17:09 UTC, saraycp commented on src/api/app/controllers/webui/webui_controller.rb
> +                   add_return_to_parameter_to_query(url: CONFIG['proxy_auth_login_page'], paramter_name: 'url')
```suggestion
                   add_return_to_parameter_to_query(url: CONFIG['proxy_auth_login_page'], parameter_name: 'ReturnTo')
                 when :ichain
                   add_return_to_parameter_to_query(url: CONFIG['proxy_auth_login_page'], parameter_name: 'url')
```

2023-12-12 17:09 UTC, saraycp commented on src/api/app/controllers/webui/webui_controller.rb
> +    return_to[paramter_name] = request.fullpath
```suggestion
  def add_return_to_parameter_to_query(url:, parameter_name:)
    uri = URI(url)
    return_to = {}
    return_to[parameter_name] = request.fullpath
```

2023-12-13 11:49 UTC, eduardoj commented
There is a typo in the description of the second commit: `Configurtion.anonymous`. It should be `Configuration.anonymous`.

2023-12-13 12:51 UTC, eduardoj requested changes
Only a small typo in the description commit. See comment below...

2023-12-13 12:52 UTC, saraycp approved these changes
I did some debugging and ended up with a URL like `http://idp.com?ReturnTo=%2Fproject%2Fshow%2Fhome%3AAdmin` when `Configuration.anonymous` is false and `:mellon` is set.

LGTM

2023-12-14 11:54 UTC, hennevogel commented
@eduardoj pushed the typo fix

2023-12-14 12:14 UTC, eduardoj approved these changes

2023-12-20 12:21 UTC, merged