[backend] change default compression for createrepo to gz
openSUSE/open-build-service pull request #15540
Opened 2024-01-24 11:33 UTC by M0ses

According to the documentation, the correct option for createrepo_c to compress also primary/filelists/other xml files with gz compression is `--general-compress-type=gz`

Taken from `createrepo_c --help`:

```
--general-compress-type=COMPRESSION_TYPE     Which compression type to use (even for primary, filelists and other xml).
```

2024-01-24 11:33 UTC, M0ses commented
Please only review - I will merge myself after some proper testing

2024-01-24 12:35 UTC, adrianschroeter commented
good finding, the minitest is most likely failing because we do not have a new enough createrepo/modifyrepo in OSU.

2024-01-24 12:36 UTC, adrianschroeter approved these changes

2024-01-24 12:41 UTC, adrianschroeter commented
modifyrepo only knows compress-type, so we must handling the parameters different now

2024-01-24 12:42 UTC, adrianschroeter requested changes
modifyrepo parameters are different now as createrepo ones. --compress-type must stay there.

You should maybe also require a recent version of createrepo in the obs-server package now.

2024-01-26 14:53 UTC, M0ses commented
> modifyrepo parameters are different now as createrepo ones. --compress-type must stay there.

Next commit should take care

> You should maybe also require a recent version of createrepo in the obs-server package now.

`--general-compression-type` is part of createrepo_c since version 0.9, so I don`t see any need to require a specific version.

2024-01-30 12:37 UTC, adrianschroeter approved these changes

2024-02-07 10:30 UTC, merged