Allow setting logo in the admin config
openSUSE/open-build-service pull request #16006
Opened 2024-04-17 10:48 UTC by hellcp-work

Lets you change the logo in the frontend
![Screenshot from 2024-04-17 12-48-36](https://github.com/openSUSE/open-build-service/assets/114928900/5eb75556-55b6-47d3-bec4-249d811b7553)

For reviewers: https://obs-reviewlab.opensuse.org/hellcp-work-logo-upload-ui/configuration

2024-06-06 14:02 UTC, krauselukas requested changes
![image](https://github.com/openSUSE/open-build-service/assets/22001671/1c996064-e485-4a2f-99f7-7adef093f22b)
@hellcp-work I get an error when I try to update the logo

2024-06-10 06:57 UTC, eduardoj commented
> @hellcp-work I get an error when I try to update the logo

@krauselukas, the error was related to the cache. I added a couple of commits. It should work now.

Just a couple of things:
- Will we provide a way to reset the image to the default?
- I tried to upload an SVG file and it didn't work.

2024-06-12 12:41 UTC, krauselukas commented on src/api/app/models/configuration.rb
> +    Rails.cache.delete('configurations/1')
@eduardoj with the switch from `fetch` to `delete` we will end up with an empty cache. Shouldn't we write it to the cache afterwards?

2024-06-12 12:45 UTC, krauselukas commented on src/api/app/models/configuration.rb
> +    Rails.cache.delete('configurations/1')
because the fetch used `force` to cause rewrite, this is not given anymore

2024-06-14 13:52 UTC, krauselukas commented on src/api/app/models/configuration.rb
> +    Rails.cache.delete('configurations/1')
alright

2024-06-14 14:20 UTC, merged