Transform the accordion reviews component into a partial
openSUSE/open-build-service pull request #16277
Opened 2024-06-06 12:08 UTC by danidoni

We move some logic into BsRequest because we're asking too much information to it and to its reviews. That could live there and just tell request to do it for us.

The component per se, has almost no logic and we're not reusing it anywhere else.

2024-06-13 11:34 UTC, krauselukas reviewed
@danidoni you forgot to delete the `html.haml` file of the accordion component. There is also the `accordion-reviews-component.scss` stylesheet. Maybe it should also be renamed.

2024-06-14 08:07 UTC, danidoni commented
> @danidoni you forgot to delete the `html.haml` file of the accordion component. There is also the `accordion-reviews-component.scss` stylesheet. Maybe it should also be renamed.

Deleted the scss file. Good catch!

> [EDIT]: sorry, I just couldn't read the diff, it didn't showed up as a delete, but as moved to the partial. so all good, I would just rename the scss file.

Yeah, I don't understand why does that sometimes...

2024-06-14 12:32 UTC, krauselukas requested changes
![image](https://github.com/openSUSE/open-build-service/assets/22001671/51196da9-c4da-478d-896d-0758971e351d)

2024-06-14 12:33 UTC, krauselukas commented
@danidoni are you sure the css code can be removed? is it not used in the partial?

2024-06-17 12:40 UTC, danidoni commented
> @danidoni are you sure the css code can be removed? is it not used in the partial? my review was more about the naming of the file :)

My bad :see_no_evil: Fixed

2024-06-17 13:12 UTC, krauselukas commented on src/api/app/assets/stylesheets/webui/accordion-reviews-component.scss
@danidoni this cannot be dropped, the css code is still used. I would just rename it, or move the code somewhere.

2024-06-18 08:05 UTC, danidoni commented on src/api/app/assets/stylesheets/webui/accordion-reviews-component.scss
Alright, I added the scss file again. Now it looks like before.

2024-06-21 10:41 UTC, krauselukas approved these changes

2024-06-21 10:41 UTC, merged