Bugfix: let target maintainer revoke an incoming request
openSUSE/open-build-service pull request #16423
Opened 2024-06-27 13:48 UTC by ncounter

Fixes https://github.com/openSUSE/open-build-service/issues/16105

2024-06-27 14:23 UTC, hennevogel requested changes

2024-06-27 14:23 UTC, hennevogel commented on src/api/app/policies/bs_request_policy.rb
> +    (author? || record.is_target_maintainer?(user)) && record.state.in?(%i[new review declined])
```suggestion
    return false if [:new, :review, :declined].exclude?(record.state)

    author? || record.is_target_maintainer?(user)
```

2024-06-27 14:23 UTC, hennevogel commented on src/api/app/policies/bs_request_policy.rb
> +    (author? || record.is_target_maintainer?(user)) && record.state.in?(%i[new review declined])
What does `BsRequestPermissionCheck` say about this case?

2024-06-28 07:39 UTC, adrianschroeter commented
this might be a not wanted regression, please see the reported issue.

2024-07-01 09:04 UTC, ncounter commented
Based on @adrianschroeter and @hennevogel comments, I moved the implementation from _allowing users with write permission in the target_ to _allowing users with write permission in the sources_ instead, according to already existing rules.

2024-07-01 15:40 UTC, hennevogel requested changes

2024-07-02 07:44 UTC, ncounter commented on src/api/app/policies/bs_request_policy.rb
> +    author? || record.is_target_maintainer?(user) || record.is_source_maintainer?(user)
It allows the `RequestDecisionComponent` to render first (https://github.com/openSUSE/open-build-service/blob/master/src/api/app/components/request_decision_component.rb#L13). Later on inside the component every request action is warded by an additional check, like the `revoke_request?` one we need here.

2024-07-02 14:18 UTC, hennevogel commented on src/api/app/policies/bs_request_policy.rb
> +    author? || record.is_target_maintainer?(user) || record.is_source_maintainer?(user)
I don't like that we deviate from the non beta UI but okay...

2024-07-02 14:19 UTC, hennevogel approved these changes

2024-07-02 14:19 UTC, merged