Apply the involvement filter without overriding requests
openSUSE/open-build-service pull request #16530
Opened 2024-07-19 12:06 UTC by hellcp-work

2024-07-19 12:08 UTC, ncounter approved these changes

2024-07-22 15:23 UTC, eduardoj commented on src/api/app/controllers/concerns/webui/requests_filter.rb
> +      requests.where(User.session.incoming_requests)
```suggestion
      requests.where(id: User.session.incoming_requests)
```

2024-07-22 15:24 UTC, eduardoj requested changes

2024-07-22 15:24 UTC, eduardoj commented on src/api/app/controllers/concerns/webui/requests_filter.rb
> +      requests.where(User.session.outgoing_requests)
```suggestion
      requests.where(id: User.session.outgoing_requests)
```
I realized this was failiing when working on #16540. I added the fixed code there, as a separate commit.

2024-07-26 14:27 UTC, eduardoj commented on src/api/app/controllers/concerns/webui/requests_filter.rb
> +      requests.where(User.session.outgoing_requests)
I don't think so.

2024-07-26 15:43 UTC, closed without merging