Provide some labels for helping in development
openSUSE/open-build-service pull request #16616
Opened 2024-08-02 09:33 UTC by danidoni

2024-08-05 15:58 UTC, hennevogel commented
I don't get those rake tasks that wrap `create`. What are they good for?

2024-08-05 15:59 UTC, danidoni commented
> I don't get those rake tasks that wrap `create`. What are they good for?

So you can do `rake dev:label_templates:data[10]` and have 10 label templates ready on dev

2024-08-06 08:20 UTC, danidoni commented
> I don't get those rake tasks that wrap `create`. What are they good for?

In the end I remove the task. It's not really providing much.

2024-08-06 09:12 UTC, danidoni commented on src/api/spec/factories/label_template.rb
> +    color { (rand * 0xffffff).to_i.to_s(16) } # Random value from 0x000000 - 0xffffff
Yes it does indeed.

2024-08-06 09:42 UTC, saraycp commented
I re-ran the feature specs. Don't forget to squash the commits, please.

2024-08-06 10:20 UTC, hennevogel requested changes

2024-08-06 10:20 UTC, hennevogel commented on src/api/lib/tasks/dev.rake
> +      5.times { create(:label_template, project: home_admin) }
https://thoughtbot.github.io/factory_bot/building-or-creating-multiple-records/summary.html

2024-08-06 10:56 UTC, danidoni commented on src/api/lib/tasks/dev.rake
> +      5.times { create(:label_template, project: home_admin) }
Applied

2024-08-06 11:17 UTC, saraycp approved these changes

2024-08-06 15:16 UTC, hennevogel approved these changes

2024-08-06 15:16 UTC, merged