Implement blame view for files
openSUSE/open-build-service pull request #16873
Opened 2024-09-20 10:31 UTC by hellcp-work

Allows for blaming files in the webui

2025-03-10 10:57 UTC, hennevogel requested changes

2025-03-10 10:57 UTC, hennevogel commented on src/api/app/controllers/webui/packages/files_controller.rb
> +        blame_parsed = blame_file.each_line.to_a.filter_map { |l| /^\s*(?<file>\d*:)?(?<revision>\d*)\s\((?<login>\S+)\s+(?<date>[\d-]+)\s(?<time>[\d:]+)\s+(?<line>\d+)\)\s(?<content>.*)$/.match(l) }
Please describe the purpose of this regex in a comment above...

2025-03-10 10:57 UTC, hennevogel commented on src/api/app/lib/backend/api/sources/package.rb
> +          http_get(['/source/:project/:package/:filename', project_name, package_name, file_name], params: options, accepted: %i[meta deleted expand rev view])
This is an API abstraction, I would say views warrant their own methods. Most likely one the includes all the parsing you do in the `FilesController`?

2025-03-10 11:01 UTC, hellcp-work commented on src/api/app/lib/backend/api/sources/package.rb
> +          http_get(['/source/:project/:package/:filename', project_name, package_name, file_name], params: options, accepted: %i[meta deleted expand rev view])
That's fair

2025-03-10 12:20 UTC, hellcp-work commented on src/api/app/controllers/webui/packages/files_controller.rb
> +        blame_parsed = blame_file.each_line.to_a.filter_map { |l| /^\s*(?<file>\d*:)?(?<revision>\d*)\s\((?<login>\S+)\s+(?<date>[\d-]+)\s(?<time>[\d:]+)\s+(?<line>\d+)\)\s(?<content>.*)$/.match(l) }
I broke it apart to make it a bit clearer, what do you think?

2025-03-10 12:20 UTC, hellcp-work commented on src/api/app/lib/backend/api/sources/package.rb
> +          http_get(['/source/:project/:package/:filename', project_name, package_name, file_name], params: options, accepted: %i[meta deleted expand rev view])
Created a new method

2025-03-10 14:47 UTC, hennevogel commented on src/api/app/controllers/webui/packages/files_controller.rb
> +          match_line.match(l)
Guess this screams for a backend feature for structured blame data...

2025-03-12 10:40 UTC, hellcp-work commented on src/api/app/controllers/webui/packages/files_controller.rb
> +          match_line.match(l)
I wrote a very simple spec for it

2025-03-13 11:38 UTC, hellcp-work commented on src/api/spec/controllers/webui/packages/files_controller_spec.rb
> +  describe 'GET #blame' do
They all come from the fixture

2025-03-13 11:47 UTC, hennevogel commented on src/api/spec/controllers/webui/packages/files_controller_spec.rb
> +  describe 'GET #blame' do
Sure but can you at least assign them to some speaking variable name or add comments or something? :)

2025-03-13 11:53 UTC, hellcp-work commented on src/api/spec/controllers/webui/packages/files_controller_spec.rb
> +  describe 'GET #blame' do
Added a comment to say where you can find corresponding data in the blame fixture

2025-03-13 12:32 UTC, hennevogel approved these changes

2025-03-14 10:26 UTC, merged