Change default value for available column from architectures table to…
openSUSE/open-build-service pull request #16897
Opened 2024-09-27 14:48 UTC by danidoni

… false

That way we stop having three values for that column: true, false and null, and we can get rid of the issue in the
database_consistencty.todo.yml

2025-03-12 08:10 UTC, rubhanazeem submitted a review, later dismissed

2025-03-12 08:26 UTC, rubhanazeem commented on src/api/db/data/20250312082028_set_architectures_available_field_to_false.rb
> +    Architecture.all.each {|architecture| architecture.update!(available: false) }
`Architecture.where(available: nil).update_all(available: false)`

2025-03-12 08:42 UTC, danidoni commented on src/api/db/data/20250312082028_set_architectures_available_field_to_false.rb
> +    Architecture.all.each {|architecture| architecture.update!(available: false) }
Fixed

2025-03-13 13:50 UTC, eduardoj requested changes

2025-03-13 13:50 UTC, eduardoj commented on .rubocop_todo.yml
> +# on 2025-03-13 13:41:46 UTC using RuboCop version 1.74.0.
After a rebase, you shouldn't have any changes like this...

2025-03-13 14:15 UTC, danidoni commented on .rubocop_todo.yml
> +# on 2025-03-13 13:41:46 UTC using RuboCop version 1.74.0.
Ah, true...

2025-03-13 14:22 UTC, eduardoj commented on .rubocop_todo.yml
> +# on 2025-03-13 13:41:46 UTC using RuboCop version 1.74.0.
Because in master the last run of RuboCop was already with 1.74.0. See: https://github.com/openSUSE/open-build-service/pull/17436/files#diff-0e154e6de9b468b91b4e5069a97429580fc41751e8fb057811017951d4753bf7R3

2025-03-13 14:36 UTC, danidoni commented on .rubocop_todo.yml
> +# on 2025-03-13 13:41:46 UTC using RuboCop version 1.74.0.
Ah, I know, you are linking `src/api/.rubocop_todo.yml` and the file we're discussing over is `.rubocop_todo.yml`. I'll rebase again though...

2025-03-13 16:28 UTC, eduardoj commented on src/api/.rubocop_todo.yml
> +    - 'db/data/20250312082028_set_architectures_available_field_to_false.rb'
This, I don't get it. This PR introduces a data migration, and you include it into the RuboCop TODO file... Does it mean we should address this new offense in the TODO file later on?

2025-03-14 08:57 UTC, danidoni commented on src/api/.rubocop_todo.yml
> +    - 'db/data/20250312082028_set_architectures_available_field_to_false.rb'
No, we won't. It's in the todo file because rubocop complaints about using `update_all` and thus bypassing the validations, but we are ok in not doing so here.

Maybe it's better to just write a comment in the data migration and remove it from the rubocop todo file if we aren't going to fix it...

2025-03-14 10:30 UTC, danidoni commented on src/api/.rubocop_todo.yml
> +    - 'db/data/20250312082028_set_architectures_available_field_to_false.rb'
What about now?

2025-03-14 11:25 UTC, eduardoj commented on src/api/.rubocop_todo.yml
> +    - 'db/data/20250312082028_set_architectures_available_field_to_false.rb'
Now it looks good to me. :+1:

2025-03-14 11:25 UTC, eduardoj approved these changes

2025-03-14 13:27 UTC, merged